import { useState, useRef } from 'react';
import { Upload, Download, AlertCircle, CheckCircle, Loader, X, MapPin, Eye, Plus, Trash2 } from 'lucide-react';
import './App.css';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface TourStop {
  name: string;
  city: string;
  address: string;
  lat: number;
  lon: number;
  region: string;
  imageUrl: string;
}

interface ParsedRow extends TourStop {
  _needsGeocode: boolean;
  _geocodeStatus: 'pending' | 'success' | 'failed' | 'skipped';
  _rowIndex: number;
}

interface CityEntry {
  id: number;
  name: string;
  lat: number;
  lon: number;
  status: 'loading' | 'success' | 'failed';
}

// ─── Constants ───────────────────────────────────────────────────────────────

const NOMINATIM_DELAY = 1100;

const US_STATES = [
  'Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut',
  'Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa',
  'Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan',
  'Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire',
  'New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio',
  'Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota',
  'Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia',
  'Wisconsin','Wyoming',
];

const SAMPLE_CSV = `name,city,address,lat,lon,region,imageUrl
Gus's Drug Mural,Georgetown,"702 e university ave, Georgetown, TX",30.6327,-97.6769,Central,https://example.com/stop1.jpg
Old Taylor High School,Taylor,"410 west 7th st, Taylor, TX",30.5705,-97.4094,Central,https://example.com/stop2.jpg
Some Stop Without Coords,Austin,"100 Congress Ave, Austin, TX",,,Central,`;

// ─── Helpers ─────────────────────────────────────────────────────────────────

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const geocodeAddress = async (address: string): Promise<{ lat: number; lon: number } | null> => {
  try {
    const res = await fetch(
      `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(address)}&format=json&limit=1`,
      { headers: { 'Accept-Language': 'en' } }
    );
    const data = await res.json();
    if (data?.length > 0) {
      return { lat: parseFloat(data[0].lat), lon: parseFloat(data[0].lon) };
    }
    return null;
  } catch {
    return null;
  }
};

const parseCSV = (text: string): ParsedRow[] => {
  const lines = text.trim().split('\n');
  if (lines.length < 2) return [];
  const headers = lines[0].split(',').map(h => h.trim().toLowerCase().replace(/['"]/g, ''));

  return lines.slice(1).map((line, idx) => {
    const values: string[] = [];
    let current = '';
    let inQuotes = false;
    for (const char of line) {
      if (char === '"') { inQuotes = !inQuotes; }
      else if (char === ',' && !inQuotes) { values.push(current.trim()); current = ''; }
      else { current += char; }
    }
    values.push(current.trim());

    const get = (key: string) => {
      const i = headers.indexOf(key);
      return i >= 0 ? (values[i] || '').replace(/^"|"$/g, '').trim() : '';
    };

    const lat = parseFloat(get('lat')) || 0;
    const lon = parseFloat(get('lon')) || 0;
    const needsGeocode = lat === 0 && lon === 0;

    return {
      name: get('name'), city: get('city'), address: get('address'),
      lat, lon, region: get('region'),
      imageUrl: get('imageurl') || get('image_url') || get('imageUrl') || '',
      _needsGeocode: needsGeocode,
      _geocodeStatus: (needsGeocode ? 'pending' : 'skipped') as ParsedRow['_geocodeStatus'],
      _rowIndex: idx,
    };
  }).filter(row => row.name);
};

const generateStopsTypeScript = (stops: TourStop[]): string => {
  const lines = stops.map(stop => `  { 
    name: ${JSON.stringify(stop.name)}, 
    city: ${JSON.stringify(stop.city)}, 
    address: ${JSON.stringify(stop.address)}, 
    lat: ${stop.lat}, 
    lon: ${stop.lon}, 
    region: ${JSON.stringify(stop.region)},
    imageUrl: ${JSON.stringify(stop.imageUrl)}
  }`);
  return `export interface TourStop {
  name: string;
  city: string;
  address: string;
  lat: number;
  lon: number;
  region: string;
  imageUrl: string;
}

export const baseStops: TourStop[] = [
${lines.join(',\n')}
];
`;
};

const generateCoordsTypeScript = (stateName: string, cities: { name: string; lat: number; lon: number }[]): string => {
  const lines = cities.map(c => `  ${JSON.stringify(c.name)}: { lat: ${c.lat}, lon: ${c.lon} },`);
  return `// City coordinates for ${stateName}
// Auto-generated by Tour Stop Importer

export const cityCoordinates: Record<string, { lat: number; lon: number }> = {
${lines.join('\n')}
};
`;
};

const downloadFile = (content: string, filename: string, type = 'text/plain') => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
};

// ─── Manual Stop Form ────────────────────────────────────────────────────────

const EMPTY_FORM = { name: '', city: '', address: '', region: '', imageUrl: '' };

interface ManualForm {
  name: string;
  city: string;
  address: string;
  region: string;
  imageUrl: string;
}

// ─── Import Tab ───────────────────────────────────────────────────────────────

function ImportTab() {
  // CSV state
  const [stops, setStops] = useState<ParsedRow[]>([]);
  const [lookupCoords, setLookupCoords] = useState(true);
  const [isGeocoding, setIsGeocoding] = useState(false);
  const [geocodeProgress, setGeocodeProgress] = useState(0);
  const [geocodeTotal, setGeocodeTotal] = useState(0);
  const [fileName, setFileName] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);

  // Manual entry state
  const [form, setForm] = useState<ManualForm>(EMPTY_FORM);
  const [formError, setFormError] = useState('');
  const [isAdding, setIsAdding] = useState(false);
  const [nextManualIdx, setNextManualIdx] = useState(-1); // negative = manual entry

  // Output state
  const [generated, setGenerated] = useState('');
  const [showPreview, setShowPreview] = useState(false);

  const loadFile = (file: File) => {
    setFileName(file.name); setGenerated(''); setShowPreview(false);
    const reader = new FileReader();
    reader.onload = (ev) => {
      const parsed = parseCSV(ev.target?.result as string);
      // Merge: keep manual entries (negative rowIndex), replace CSV entries
      setStops(prev => [...prev.filter(s => s._rowIndex < 0), ...parsed]);
    };
    reader.readAsText(file);
  };

  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]; if (file) loadFile(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const file = e.dataTransfer.files?.[0];
    if (file?.name.endsWith('.csv')) loadFile(file);
  };

  const removeStop = (rowIndex: number) =>
    setStops(prev => prev.filter(s => s._rowIndex !== rowIndex));

  const setField = (field: keyof ManualForm, value: string) => {
    setForm(prev => ({ ...prev, [field]: value }));
    setFormError('');
  };

  const handleAddManual = async () => {
    if (!form.name.trim()) { setFormError('Name is required'); return; }
    if (!form.city.trim()) { setFormError('City is required'); return; }
    if (!form.address.trim()) { setFormError('Address is required'); return; }
    if (!form.region.trim()) { setFormError('Region is required'); return; }
    if (stops.some(s => s.name.toLowerCase() === form.name.trim().toLowerCase())) {
      setFormError('A stop with this name already exists'); return;
    }

    setFormError('');
    setIsAdding(true);

    const idx = nextManualIdx;
    setNextManualIdx(prev => prev - 1);

    // Add placeholder immediately
    const placeholder: ParsedRow = {
      name: form.name.trim(), city: form.city.trim(),
      address: form.address.trim(), region: form.region.trim(),
      imageUrl: form.imageUrl.trim(), lat: 0, lon: 0,
      _needsGeocode: true, _geocodeStatus: 'pending', _rowIndex: idx,
    };
    setStops(prev => [...prev, placeholder]);
    setForm(EMPTY_FORM);

    // Geocode
    await sleep(NOMINATIM_DELAY);
    const result = await geocodeAddress(`${placeholder.address}, ${placeholder.city}`);
    setStops(prev => prev.map(s => s._rowIndex !== idx ? s : {
      ...s, lat: result?.lat ?? 0, lon: result?.lon ?? 0,
      _needsGeocode: false,
      _geocodeStatus: (result ? 'success' : 'failed') as ParsedRow['_geocodeStatus'],
    }));
    setIsAdding(false);
  };

  const handleGenerate = async () => {
    let workingStops = [...stops];
    if (lookupCoords) {
      const needsGeocode = workingStops.filter(s => s._needsGeocode);
      if (needsGeocode.length > 0) {
        setIsGeocoding(true); setGeocodeTotal(needsGeocode.length); setGeocodeProgress(0);
        for (let i = 0; i < workingStops.length; i++) {
          const stop = workingStops[i];
          if (!stop._needsGeocode) continue;
          const result = await geocodeAddress(`${stop.address}, ${stop.city}`);
          workingStops[i] = {
            ...stop, lat: result?.lat ?? 0, lon: result?.lon ?? 0,
            _geocodeStatus: (result ? 'success' : 'failed') as ParsedRow['_geocodeStatus'],
          };
          setStops([...workingStops]);
          setGeocodeProgress(prev => prev + 1);
          await sleep(NOMINATIM_DELAY);
        }
        setIsGeocoding(false);
      }
    }
    const ts = generateStopsTypeScript(
      workingStops.map(({ name, city, address, lat, lon, region, imageUrl }) =>
        ({ name, city, address, lat, lon, region, imageUrl }))
    );
    setGenerated(ts); setShowPreview(true);
  };

  const handleDownloadCSV = () => {
    const rows = stops.map(s => [
      `"${s.name}"`, `"${s.city}"`, `"${s.address}"`,
      s.lat || '', s.lon || '',
      `"${s.region}"`, `"${s.imageUrl}"`,
    ].join(','));
    const csv = ['name,city,address,lat,lon,region,imageUrl', ...rows].join('\n');
    downloadFile(csv, 'tour_stops.csv', 'text/csv');
  };

  const needsGeocodeCount = stops.filter(s => s._needsGeocode).length;
  const geocodedCount = stops.filter(s => s._geocodeStatus === 'success').length;
  const failedCount = stops.filter(s => s._geocodeStatus === 'failed').length;

  return (
    <div>
      {/* Format Info */}
      <div className="card">
        <p className="card-title" style={{ marginBottom: '0.5rem' }}>Expected CSV columns (row 1 = header)</p>
        <p className="format-mono">name, city, address, lat, lon, region, imageUrl</p>
        <p className="format-info">
          <strong>lat</strong> / <strong>lon</strong> / <strong>imageUrl</strong> can be empty.&nbsp;
          <strong>distance</strong> is calculated automatically by the app.
        </p>
        <button className="btn-ghost mt-sm" onClick={() => downloadFile(SAMPLE_CSV, 'sample_stops.csv', 'text/csv')}>
          <Download size={14} /> Download Sample CSV
        </button>
      </div>

      {/* Drop Zone */}
      <div
        className={`drop-zone ${fileName ? 'has-file' : ''}`}
        onDrop={handleDrop}
        onDragOver={(e) => e.preventDefault()}
        onClick={() => fileRef.current?.click()}
      >
        <input ref={fileRef} type="file" accept=".csv" onChange={handleFile} style={{ display: 'none' }} />
        <Upload size={32} className="drop-zone-icon" />
        {fileName ? (
          <>
            <p className="drop-zone-filename">{fileName}</p>
            <p className="drop-zone-hint">{stops.filter(s => s._rowIndex >= 0).length} stops from CSV — click to replace</p>
          </>
        ) : (
          <>
            <p className="drop-zone-label">Drop your CSV here or click to browse</p>
            <p className="drop-zone-hint">Optional — you can also add stops manually below</p>
          </>
        )}
      </div>

      {/* Manual Entry Form */}
      <div className="card">
        <p className="section-title">Add Stop Manually</p>
        <div className="manual-grid">
          <div>
            <label className="field-label">Stop Name *</label>
            <input className="input" type="text" value={form.name} onChange={e => setField('name', e.target.value)} placeholder="e.g. Gus's Drug Mural" />
          </div>
          <div>
            <label className="field-label">City *</label>
            <input className="input" type="text" value={form.city} onChange={e => setField('city', e.target.value)} placeholder="e.g. Georgetown" />
          </div>
          <div>
            <label className="field-label">Address *</label>
            <input className="input" type="text" value={form.address} onChange={e => setField('address', e.target.value)} placeholder="e.g. 702 E University Ave, Georgetown, TX" />
          </div>
          <div>
            <label className="field-label">Region *</label>
            <input className="input" type="text" value={form.region} onChange={e => setField('region', e.target.value)} placeholder="e.g. Central" />
          </div>
          <div style={{ gridColumn: '1 / -1' }}>
            <label className="field-label">Image URL <span>(optional)</span></label>
            <input className="input" type="text" value={form.imageUrl} onChange={e => setField('imageUrl', e.target.value)} placeholder="https://..." />
          </div>
        </div>
        {formError && <p className="field-error mt-sm"><AlertCircle size={12} /> {formError}</p>}
        <button
          className="btn btn-green mt-md"
          onClick={handleAddManual}
          disabled={isAdding}
        >
          {isAdding ? <Loader size={16} className="spin" /> : <Plus size={16} />}
          {isAdding ? 'Looking up coordinates...' : 'Add Stop'}
        </button>
      </div>

      {stops.length > 0 && (
        <>
          {/* Options */}
          <div className="card row between wrap">
            <label style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', cursor: 'pointer' }}>
              <input
                type="checkbox" checked={lookupCoords}
                onChange={(e) => setLookupCoords(e.target.checked)}
                style={{ width: '18px', height: '18px', accentColor: '#fb923c' }}
              />
              <span>
                <span style={{ color: '#f1f5f9', fontWeight: 500 }}>Look up missing coordinates on generate</span>
                <span style={{ color: '#64748b', fontSize: '0.8rem', display: 'block' }}>
                  {needsGeocodeCount} stop{needsGeocodeCount !== 1 ? 's' : ''} still need coordinates
                </span>
              </span>
            </label>
            <span className="card-meta">{stops.length} total stops</span>
          </div>

          {/* Geocode Progress */}
          {isGeocoding && (
            <div className="card" style={{ borderColor: 'rgba(251,146,60,0.3)' }}>
              <div className="row center mb-sm">
                <Loader size={18} className="spin" style={{ color: '#fb923c' }} />
                <span style={{ color: '#fb923c', fontWeight: 500 }}>
                  Looking up coordinates... {geocodeProgress} / {geocodeTotal}
                </span>
              </div>
              <div className="progress-bar-track">
                <div className="progress-bar-fill" style={{ width: `${(geocodeProgress / geocodeTotal) * 100}%` }} />
              </div>
            </div>
          )}

          {/* Geocode Results */}
          {!isGeocoding && (geocodedCount > 0 || failedCount > 0) && (
            <div className="badge-row">
              {geocodedCount > 0 && <span className="badge badge-success"><CheckCircle size={14} /> {geocodedCount} coordinates found</span>}
              {failedCount > 0 && <span className="badge badge-error"><AlertCircle size={14} /> {failedCount} failed (set to 0,0)</span>}
            </div>
          )}

          {/* Preview Table */}
          <div className="card-no-pad">
            <div className="card-header">
              <span className="card-title">Stop List</span>
              <span className="card-meta">{stops.length} stops ({stops.filter(s => s._rowIndex < 0).length} manual)</span>
            </div>
            <div style={{ overflowX: 'auto' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    {['', 'Name', 'City', 'Address', 'Region', 'Coords', ''].map((h, i) => (
                      <th key={i}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {stops.map((stop) => (
                    <tr key={stop._rowIndex} className={stop._geocodeStatus === 'failed' ? 'row-error' : stop._geocodeStatus === 'success' ? 'row-success' : ''}>
                      <td>
                        {stop._rowIndex < 0
                          ? <span title="Manual entry"><Plus size={12} style={{ color: '#fb923c' }} /></span>
                          : <span title="From CSV"><Upload size={12} style={{ color: '#64748b' }} /></span>
                        }
                      </td>
                      <td className="td-name">{stop.name}</td>
                      <td className="td-muted">{stop.city}</td>
                      <td className="td-muted" style={{ fontSize: '0.8rem', maxWidth: '200px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{stop.address}</td>
                      <td className="td-blue">{stop.region}</td>
                      <td>
                        {stop._geocodeStatus === 'pending' && <span className="td-warn">needs lookup</span>}
                        {stop._geocodeStatus === 'success' && <span className="td-mono" style={{ fontSize: '0.75rem' }}>{stop.lat.toFixed(3)}, {stop.lon.toFixed(3)}</span>}
                        {stop._geocodeStatus === 'failed' && <span className="td-error">failed (0,0)</span>}
                        {stop._geocodeStatus === 'skipped' && <span className="td-mono" style={{ fontSize: '0.75rem' }}>{stop.lat.toFixed(3)}, {stop.lon.toFixed(3)}</span>}
                      </td>
                      <td>
                        <button className="btn-icon" onClick={() => removeStop(stop._rowIndex)} title="Remove stop">
                          <X size={14} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Actions */}
          <div className="row wrap mb-md">
            <button className="btn btn-orange" onClick={handleGenerate} disabled={isGeocoding || stops.length === 0}>
              {isGeocoding ? <Loader size={18} className="spin" /> : <CheckCircle size={18} />}
              {isGeocoding ? 'Processing...' : 'Generate tourStops.ts'}
            </button>
            <button className="btn btn-green" onClick={handleDownloadCSV} disabled={stops.length === 0}>
              <Download size={18} /> Download as CSV
            </button>
            {generated && (
              <>
                <button className="btn btn-blue" onClick={() => downloadFile(generated, 'tourStops.ts')}>
                  <Download size={18} /> Download tourStops.ts
                </button>
                <button className="btn-ghost" onClick={() => setShowPreview(!showPreview)}>
                  <Eye size={18} /> {showPreview ? 'Hide' : 'Show'} Output
                </button>
              </>
            )}
          </div>

          {/* Output */}
          {generated && showPreview && (
            <div className="card-dark">
              <div className="card-header">
                <span className="card-title" style={{ fontFamily: 'monospace', fontSize: '0.9rem' }}>tourStops.ts</span>
                <button className="btn-ghost sm" onClick={() => navigator.clipboard.writeText(generated).then(() => alert('Copied!'))}>Copy</button>
              </div>
              <textarea className="output-textarea" readOnly value={generated} onClick={(e) => (e.target as HTMLTextAreaElement).select()} />
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ─── City Generator Tab ───────────────────────────────────────────────────────

function CityGeneratorTab() {
  const [stateName, setStateName] = useState('');
  const [cityInput, setCityInput] = useState('');
  const [cities, setCities] = useState<CityEntry[]>([]);
  const [validating, setValidating] = useState(false);
  const [inputError, setInputError] = useState('');
  const [generated, setGenerated] = useState('');
  const [showPreview, setShowPreview] = useState(false);
  const [nextId, setNextId] = useState(1);

  const addCity = async () => {
    const name = cityInput.trim();
    if (!name) return;
    if (!stateName) { setInputError('Please select a state first'); return; }
    if (cities.some(c => c.name.toLowerCase() === name.toLowerCase())) {
      setInputError('City already in list'); return;
    }
    if (cities.length >= 20) { setInputError('Maximum 20 cities reached'); return; }

    setInputError('');
    setValidating(true);
    setCityInput('');

    const id = nextId;
    setNextId(prev => prev + 1);
    setCities(prev => [...prev, { id, name, lat: 0, lon: 0, status: 'loading' }]);

    await sleep(NOMINATIM_DELAY);
    const result = await geocodeAddress(`${name}, ${stateName}, USA`);

    setCities(prev => prev.map(c => c.id !== id ? c : {
      ...c, lat: result?.lat ?? 0, lon: result?.lon ?? 0, status: result ? 'success' : 'failed',
    }));
    setValidating(false);
  };

  const removeCity = (id: number) => setCities(prev => prev.filter(c => c.id !== id));

  const retryCity = async (id: number) => {
    const city = cities.find(c => c.id === id);
    if (!city) return;
    setCities(prev => prev.map(c => c.id !== id ? c : { ...c, status: 'loading' }));
    await sleep(NOMINATIM_DELAY);
    const result = await geocodeAddress(`${city.name}, ${stateName}, USA`);
    setCities(prev => prev.map(c => c.id !== id ? c : {
      ...c, lat: result?.lat ?? 0, lon: result?.lon ?? 0, status: result ? 'success' : 'failed',
    }));
  };

  const handleGenerate = () => {
    const validCities = cities
      .filter(c => c.status === 'success')
      .map(c => ({ name: c.name, lat: c.lat, lon: c.lon }));
    setGenerated(generateCoordsTypeScript(stateName, validCities));
    setShowPreview(true);
  };

  const successCount = cities.filter(c => c.status === 'success').length;

  return (
    <div>
      {/* State + City Input */}
      <div className="card">
        <p className="section-title">City Coordinates Generator</p>
        <p className="section-desc">
          Select your state, then add cities one by one. Each city is validated against Nominatim to confirm it exists and retrieve its coordinates.
        </p>

        {/* State */}
        <div className="mb-md">
          <label className="field-label">State</label>
          <select
            className="input"
            style={{ maxWidth: '300px' }}
            value={stateName}
            onChange={(e) => { setStateName(e.target.value); setCities([]); setGenerated(''); }}
          >
            <option value="">— Select a state —</option>
            {US_STATES.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
        </div>

        {/* City Input */}
        <div className="row" style={{ alignItems: 'flex-start' }}>
          <div style={{ flex: 1, minWidth: '200px' }}>
            <label className="field-label">
              City Name <span>({cities.length}/20)</span>
            </label>
            <input
              type="text"
              className="input"
              value={cityInput}
              onChange={(e) => { setCityInput(e.target.value); setInputError(''); }}
              onKeyDown={(e) => e.key === 'Enter' && addCity()}
              placeholder={stateName ? `Enter a city in ${stateName}...` : 'Select a state first...'}
              disabled={!stateName || validating || cities.length >= 20}
            />
            {inputError && (
              <p className="field-error"><AlertCircle size={12} /> {inputError}</p>
            )}
          </div>
          <button
            className="btn btn-green mt-lg"
            onClick={addCity}
            disabled={!cityInput.trim() || !stateName || validating || cities.length >= 20}
          >
            {validating ? <Loader size={16} className="spin" /> : <Plus size={16} />}
            {validating ? 'Validating...' : 'Add City'}
          </button>
        </div>
      </div>

      {/* City List */}
      {cities.length > 0 && (
        <div className="card-no-pad">
          <div className="card-header">
            <span className="card-title">City List</span>
            <span className="card-meta">{successCount} valid / {cities.length} total</span>
          </div>
          <div className="col">
            {cities.map((c) => (
              <div key={c.id} className={`city-row ${c.status}`}>
                {c.status === 'loading' && <Loader size={15} className="spin" style={{ color: '#fb923c', flexShrink: 0 }} />}
                {c.status === 'success' && <CheckCircle size={15} style={{ color: '#22c55e', flexShrink: 0 }} />}
                {c.status === 'failed'  && <AlertCircle size={15} style={{ color: '#f87171', flexShrink: 0 }} />}

                <span className={`city-name ${c.status === 'failed' ? 'failed' : ''}`}>{c.name}</span>

                {c.status === 'success' && <span className="city-coords">{c.lat.toFixed(4)}, {c.lon.toFixed(4)}</span>}
                {c.status === 'failed'  && <button className="btn-ghost" style={{ fontSize: '0.75rem', padding: '0.2rem 0.5rem' }} onClick={() => retryCity(c.id)}>Retry</button>}
                {c.status === 'loading' && <span className="city-status-text">looking up...</span>}

                <button className="btn-icon" onClick={() => removeCity(c.id)}><Trash2 size={14} /></button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Actions */}
      {successCount > 0 && (
        <>
          <div className="row wrap mb-md">
            <button className="btn btn-orange" onClick={handleGenerate}>
              <CheckCircle size={18} /> Generate cityCoordinates.ts
            </button>
            {generated && (
              <>
                <button className="btn btn-blue" onClick={() => downloadFile(generated, 'cityCoordinates.ts')}>
                  <Download size={18} /> Download
                </button>
                <button className="btn-ghost" onClick={() => setShowPreview(!showPreview)}>
                  <Eye size={18} /> {showPreview ? 'Hide' : 'Show'} Output
                </button>
              </>
            )}
          </div>

          {generated && showPreview && (
            <div className="card-dark">
              <div className="card-header">
                <span className="card-title" style={{ fontFamily: 'monospace', fontSize: '0.9rem' }}>cityCoordinates.ts</span>
                <button className="btn-ghost sm" onClick={() => navigator.clipboard.writeText(generated).then(() => alert('Copied!'))}>Copy</button>
              </div>
              <textarea className="output-textarea short" readOnly value={generated} onClick={(e) => (e.target as HTMLTextAreaElement).select()} />
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────

export default function ImportStops() {
  const [activeTab, setActiveTab] = useState<'import' | 'cities'>('import');

  return (
    <div className="importer-container">
      <div className="importer-inner">

        <div className="importer-header">
          <h1 className="importer-title">Tour Stop Importer</h1>
          <p className="importer-subtitle">
            Generate <strong>tourStops.ts</strong> and <strong>cityCoordinates.ts</strong> files for your app.
          </p>
        </div>

        <div className="tab-bar">
          <button className={`tab-btn ${activeTab === 'import' ? 'active' : ''}`} onClick={() => setActiveTab('import')}>
            <Upload size={16} /> Import Stops
          </button>
          <button className={`tab-btn ${activeTab === 'cities' ? 'active' : ''}`} onClick={() => setActiveTab('cities')}>
            <MapPin size={16} /> City Generator
          </button>
        </div>

        {activeTab === 'import' ? <ImportTab /> : <CityGeneratorTab />}
      </div>
    </div>
  );
}